chitanka_permission:
    transitions:
        -
            from: user
            to: editor
            managers: [ editor_managing, editor_chief, admin ]
        -
            from: user
            to: wiki_editor
            managers: admin
        -
            from: user
            to: admin
            managers: admin
        -
            from: editor
            to: editor_senior
            managers: [ editor_managing, editor_chief, admin ]
        -
            from: editor_senior
            to: editor_managing
            managers: [ editor_chief, admin ]
        -
            from: editor_managing
            to: editor_chief
            managers: admin
