<?php namespace App\Entity\BookField;

class Map {

	public static $fieldComponents = [
		'title' => 'titling',
		'altTitle' => 'titling',
		'subtitle' => 'titling',
		'subtitle2' => 'titling',
		'volumeTitle' => 'titling',
		'author' => 'authorship',
		'translator' => 'authorship',
		'translatedFromLanguage' => 'authorship',
		'dateOfTranslation' => 'authorship',
		'adaptedBy' => 'authorship',
		'otherAuthors' => 'authorship',
		'compiler' => 'authorship',
		'format' => 'body',
		'pageCount' => 'body',
		'binding' => 'body',
		'themes' => 'classification',
		'genre' => 'classification',
		'category' => 'classification',
		'trackingCode' => 'classification',
		'litGroup' => 'classification',
		'uniformProductClassification' => 'classification',
		'universalDecimalClassification' => 'classification',
		'isbn' => 'classification',
		'contentType' => 'content',
		'nationality' => 'content',
		'language' => 'content',
		'notesAboutOriginal' => 'content',
		'annotation' => 'content',
		'notesAboutAuthor' => 'content',
		'marketingSnippets' => 'content',
		'toc' => 'content',
		'illustrated' => 'content',
		'sequence' => 'grouping',
		'sequenceNr' => 'grouping',
		'subsequence' => 'grouping',
		'subsequenceNr' => 'grouping',
		'series' => 'grouping',
		'seriesNr' => 'grouping',
		'printingHouse' => 'print',
		'typeSettingIn' => 'print',
		'printSigned' => 'print',
		'printOut' => 'print',
		'printerSheets' => 'print',
		'publisherSheets' => 'print',
		'provisionPublisherSheets' => 'print',
		'totalPrint' => 'print',
		'chiefEditor' => 'staff',
		'managingEditor' => 'staff',
		'editor' => 'staff',
		'editorialStaff' => 'staff',
		'publisherEditor' => 'staff',
		'artistEditor' => 'staff',
		'technicalEditor' => 'staff',
		'consultant' => 'staff',
		'scienceEditor' => 'staff',
		'copyreader' => 'staff',
		'reviewer' => 'staff',
		'artist' => 'staff',
		'illustrator' => 'staff',
		'corrector' => 'staff',
		'layout' => 'staff',
		'coverLayout' => 'staff',
		'libraryDesign' => 'staff',
		'computerProcessing' => 'staff',
		'prepress' => 'staff',
		'edition' => 'publishing',
		'publisher' => 'publishing',
		'publisherCity' => 'publishing',
		'publishingYear' => 'publishing',
		'publisherAddress' => 'publishing',
		'publisherCode' => 'publishing',
		'publisherOrder' => 'publishing',
		'publisherNumber' => 'publishing',
		'price' => 'publishing',
		'notes' => 'meta',
		'infoSources' => 'meta',
		'adminComment' => 'meta',
		'ocredText' => 'meta',
		'isIncomplete' => 'meta',
		'reasonWhyIncomplete' => 'meta',
		'verified' => 'meta',
	];

	private static $fieldClasses = [
		'author' => Person::class,
		'translator' => Person::class,
		'adaptedBy' => Person::class,
		'otherAuthors' => Person::class,
		'compiler' => Person::class,
		'chiefEditor' => Person::class,
		'managingEditor' => Person::class,
		'editor' => Person::class,
		'editorialStaff' => Person::class,
		'publisherEditor' => Person::class,
		'artistEditor' => Person::class,
		'technicalEditor' => Person::class,
		'consultant' => Person::class,
		'scienceEditor' => Person::class,
		'copyreader' => Person::class,
		'reviewer' => Person::class,
		'artist' => Person::class,
		'illustrator' => Person::class,
		'corrector' => Person::class,
		'layout' => Person::class,
		'coverLayout' => Person::class,
		'libraryDesign' => Person::class,
		'computerProcessing' => Person::class,
		'prepress' => Person::class,
		'illustrated' => Illustrated::class,
		'isbn' => Isbn::class,
		'isbnClean' => IsbnClean::class,
		'publisher' => Publisher::class,
	];

	public static function classForField($field) {
		if (isset(self::$fieldClasses[$field])) {
			return self::$fieldClasses[$field];
		}
		return null;
	}
}
