vich_uploader:
    db_driver: orm
    mappings:
        book_cover:
            uri_prefix:         /scans
            upload_destination: %kernel.root_dir%/../data/scans
            namer:              vich_uploader.namer_uniqid

easy_admin:
    site_name: 'Библиоман'
    assets:
        css:
            - //cdn.rawgit.com/noelboss/featherlight/1.2.0/release/featherlight.min.css
            - css/admin.css
        js:
            - //cdn.rawgit.com/noelboss/featherlight/1.2.0/release/featherlight.min.js
            - js/admin.js
    entities:
        Книги:
            class: App\Entity\Book
            image_base_path: /thumb
            list:
                fields:
                    - { property: id, label: Номер }
                    - { property: cover, label: К, type: image }
                    - { property: backCover, label: ЗК, type: image }
                    - { property: title, label: Заглавие }
                    - { property: author, label: Автор }
                    - { property: publisher, label: Издател }
                    - { property: pubDate, label: Година }
            form:
                fields:
                    - { property: author, label: Автор, help: 'Ако са няколко, се отделят със запетая' }
                    - { property: title, label: Заглавие }
                    - { property: subtitle, label: Подзаглавие }
                    - { property: sequence, label: Поредица / Серия }
                    - { property: sequenceNr, label: № в поредица / серия }
                    - { property: translator, label: Преводач }
                    - { property: translatedFromLanguage, label: 'Език, от който е преведено' }
                    - { property: dateOfTranslation, label: 'Година на превод' }
                    - { property: compiler, label: Съставител }
                    - { property: editorialStaff, label: Редакционна колегия, help: 'Няколко се отделят със запетая' }
                    - { property: chiefEditor, label: Отговорен редактор }
                    - { property: editor, label: Редактор }
                    - { property: publisherEditor, label: Редактор на издателството }
                    - { property: consultant, label: Консултант }
                    - { property: artist, label: Художник, help: 'или Илюстрация на корицата, Художник на корицата' }
                    - { property: artistEditor, label: Художествен редактор }
                    - { property: technicalEditor, label: Технически редактор }
                    - { property: reviewer, label: Рецензент }
                    - { property: corrector, label: Коректор }
                    - { property: layout, label: Оформление }
                    - { property: coverLayout, label: Оформление на корица, help: 'или Дизайн на корицата' }
                    - { property: computerProcessing, label: Компютърна обработка, help: 'или Компютърен дизайн' }
                    - { property: prepress, label: Предпечатна подготовка }
                    - { property: publisher, label: Издател }
                    - { property: pubCity, label: Град на издателя }
                    - { property: pubDate, label: Година на издаване }
                    - { property: print, label: Печатница }
                    - { property: contentType, label: Тип, help: 'роман / сборник разкази / сборник / стихосбирка' }
                    - { property: nationality, label: Националност }
                    - { property: language, label: Език }
                    - { property: edition, label: Поредност на изданието }
                    - { property: litGroup, label: Литературна група }
                    - { property: typeSettingIn, label: Дадена за набор/печат }
                    - { property: printSigned, label: Подписана за печат }
                    - { property: printOut, label: Излязла от печат }
                    - { property: printerSheets, label: Печатни коли, help: 'среща се и като „обем“' }
                    - { property: publisherSheets, label: Издателски коли }
                    - { property: provisionPublisherSheets, label: УИК, help: Условно издателски коли }
                    - { property: format, label: Формат }
                    - { property: publisherCode, label: 'Код / Тематичен номер' }
                    - { property: trackingCode, label: Номер, help: 'От вида на „С-32“ или „Ч840“' }
                    - { property: publisherOrder, label: 'Поръчка / Издателски №' }
                    - { property: pageCount, label: Брой страници }
                    - { property: totalPrint, label: Тираж }
                    - { property: price, label: Цена }
                    - { property: binding, label: Подвързия, help: 'мека / твърда' }
                    - { property: illustrated, label: 'С илюстрации' }
                    - { property: isbn10, label: ISBN 10 }
                    - { property: isbn13, label: ISBN 13 }
                    - { property: genre, label: Жанр }
                    - { property: themes, label: Теми }
                    - { property: annotation, label: Анотация }
                    - { property: toc, label: Съдържание }
                    - { property: notes, label: Бележки }
                    - { property: notesAboutOriginal, label: 'Бележки за изданието, от което е направен преводът'  }
                    - { property: coverFile, type: file, label: Корица }
                    - { property: backCoverFile, type: file, label: Задна корица }
                    #- { property: source, label: Източник }
        #Личности: App\Entity\Person
