vich_uploader:
    db_driver: orm
    mappings:
        book_cover:
            uri_prefix:         /scans
            upload_destination: %kernel.root_dir%/../data/scans
            namer:              vich_uploader.namer_uniqid

easy_admin:
    site_name: 'Библиоман'
    design:
        theme: 'default'
        color_scheme: light
        form_theme: '@App/admin_layout.html.twig'
    assets:
        css:
            - //cdn.rawgit.com/noelboss/featherlight/1.2.0/release/featherlight.min.css
            - css/admin.css
        js:
            - //cdn.rawgit.com/noelboss/featherlight/1.2.0/release/featherlight.min.js
            - js/admin.js
    entities:
        Книги:
            class: App\Entity\Book
            image_base_path: /thumb
            list:
                actions:
                    - { name: new, label: 'Добавяне на книга', icon: plus }
                    - { name: edit, icon: pencil, label: '' }
                    - { name: show, icon: eye, label: '' }
                fields:
                    - { property: id, label: № }
                    - { property: cover, label: К, type: image }
                    - { property: backCover, label: ЗК, type: image }
                    - { property: title, label: Заглавие }
                    - { property: author, label: Автор }
                    - { property: publisher, label: Издател }
                    - { property: pubDate, label: Година }
            new:
                title: 'Добавяне на нова книга'
                action_label: 'Нова книга'
            form:
                title: 'Редактиране на книга (№%%entity_id%%)'
                fields:
                    - { property: author, label: author, help: 'Ако са няколко, се отделят със запетая' }
                    - { property: title, label: title }
                    - { property: subtitle, label: subtitle }
                    - { property: sequence, label: sequence }
                    - { property: sequenceNr, label: sequenceNr }
                    - { property: translator, label: translator }
                    - { property: translatedFromLanguage, label: translatedFromLanguage }
                    - { property: dateOfTranslation, label: dateOfTranslation }
                    - { property: compiler, label: compiler }
                    - { property: editorialStaff, label: editorialStaff, help: 'Няколко се отделят със запетая' }
                    - { property: chiefEditor, label: chiefEditor }
                    - { property: editor, label: editor }
                    - { property: publisherEditor, label: publisherEditor }
                    - { property: consultant, label: consultant }
                    - { property: artist, label: artist, help: 'или Илюстрация на корицата, Художник на корицата' }
                    - { property: artistEditor, label: artistEditor }
                    - { property: technicalEditor, label: technicalEditor }
                    - { property: reviewer, label: reviewer }
                    - { property: corrector, label: corrector }
                    - { property: layout, label: layout }
                    - { property: coverLayout, label: coverLayout, help: 'или Дизайн на корицата' }
                    - { property: computerProcessing, label: computerProcessing, help: 'или Компютърен дизайн' }
                    - { property: prepress, label: prepress }
                    - { property: publisher, label: publisher }
                    - { property: pubCity, label: pubCity }
                    - { property: pubDate, label: pubDate }
                    - { property: print, label: print }
                    - { property: contentType, label: contentType, help: 'роман / сборник разкази / сборник / стихосбирка' }
                    - { property: nationality, label: nationality }
                    - { property: language, label: language }
                    - { property: edition, label: edition }
                    - { property: litGroup, label: litGroup }
                    - { property: typeSettingIn, label: typeSettingIn }
                    - { property: printSigned, label: printSigned }
                    - { property: printOut, label: printOut }
                    - { property: printerSheets, label: printerSheets, help: 'среща се и като „обем“' }
                    - { property: publisherSheets, label: publisherSheets }
                    - { property: provisionPublisherSheets, label: provisionPublisherSheets, help: Условно издателски коли }
                    - { property: format, label: format }
                    - { property: publisherCode, label: publisherCode }
                    - { property: trackingCode, label: trackingCode, help: 'От вида на „С-32“ или „Ч840“' }
                    - { property: publisherOrder, label: publisherOrder }
                    - { property: publisherNumber, label: publisherNumber }
                    - { property: uniformProductClassification, label: uniformProductClassification, help: 'Код за единна класификация на продукцията' }
                    - { property: pageCount, label: pageCount }
                    - { property: totalPrint, label: totalPrint }
                    - { property: price, label: price }
                    - { property: binding, label: binding, help: 'мека / твърда' }
                    - { property: illustrated, label: illustrated, type: checkbox }
                    - { property: isbn10, label: isbn10 }
                    - { property: isbn13, label: isbn13 }
                    - { property: genre, label: genre }
                    - { property: themes, label: themes }
                    - { property: annotation, label: annotation }
                    - { property: marketingSnippets, label: marketingSnippets, help: 'Обикновено на задната корица' }
                    - { property: toc, label: toc }
                    - { property: notes, label: notes }
                    - { property: notesAboutOriginal, label: notesAboutOriginal, от което е направен преводът'  }
                    - { property: coverFile, label: coverFile, type: file }
                    - { property: backCoverFile, label: backCoverFile, type: file }
                    #- { property: source, label: source }
        #Личности: App\Entity\Person
