parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     biblioman
    database_user:     root
    database_password: ~

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~

    locale:            bg

    # A secret key that's used to generate certain security-related tokens
    secret:            ThisTokenIsNotSoSecretChangeIt
    sitename: Библиоман
    single_login_provider: ~

    book_fields_short:
        - authorship.author
        - titling.title
        - titling.volumeTitle
        - titling.subtitle
        - grouping.sequence
        - publishing.edition
        - category
        - classification.genre
        - authorship.translator
        - authorship.compiler
        - staff.editor
        - staff.chiefEditor
        - staff.publisherEditor
        - staff.artist
        - staff.illustrator
        - staff.artistEditor
        - staff.technicalEditor
        - publishing.publisher
        - publishing.publishingYear
        - body.binding
        - body.pageCount
        - classification.isbn
        - createdBy
    book_fields_long:
        - authorship.author
        - titling.title
        - titling.altTitle
        - titling.volumeTitle
        - titling.subtitle
        - titling.subtitle2
        - grouping.sequence
        - grouping.subsequence
        - grouping.series
        - authorship.adaptedBy
        - authorship.otherAuthors
        - content.contentType
        - content.nationality
        - content.language
        - publishing.edition
        - category
        - classification.genre
        - classification.themes
        - _divider
        - authorship.translator
        - authorship.translatedFromLanguage
        - authorship.dateOfTranslation
        - authorship.compiler
        - staff.editor
        - staff.chiefEditor
        - staff.managingEditor
        - staff.publisherEditor
        - staff.editorialStaff
        - staff.consultant
        - staff.artist
        - staff.illustrator
        - staff.artistEditor
        - staff.technicalEditor
        - staff.reviewer
        - staff.scienceEditor
        - staff.copyreader
        - staff.corrector
        - staff.layout
        - staff.coverLayout
        - staff.libraryDesign
        - staff.computerProcessing
        - staff.prepress
        - _divider
        - publishing.publisher
        - publishing.publisherCity
        - publishing.publishingYear
        - publishing.publisherAddress
        - print.printingHouse
        - otherFields
        - _divider
        - classification.litGroup
        - print.typeSettingIn
        - print.printSigned
        - print.printOut
        - print.printerSheets
        - print.publisherSheets
        - print.provisionPublisherSheets
        - body.format
        - publishing.publisherCode
        - classification.trackingCode
        - publishing.publisherOrder
        - publishing.publisherNumber
        - body.pageCount
        - print.totalPrint
        - body.binding
        - publishing.price
        - content.illustrated
        - _divider
        - classification.isbn
        - classification.uniformProductClassification
        - classification.universalDecimalClassification
        - _divider
        - content.annotation
        - content.notesAboutAuthor
        - content.marketingSnippets
        - content.toc
        - content.notesAboutOriginal
        - _divider
        - createdBy
        - createdAt
        - updatedAt
        - _divider
        - meta.notes
        - meta.infoSources
        - linksByCategory

    default_shelves:
        to-read:
            name: За прочит
            icon: fa-bookmark-o
            description: Книги за прочит
            group: Четене
        currently-reading:
            name: Четени в момента
            icon: fa-bookmark
            description: Четени в момента книги
            group: Четене
        read:
            name: Прочетени
            icon: fa-check
            description: Прочетени книги
            group: Четене
            important: true
        favorities:
            name: Любими
            icon: fa-star
            description: Любими книги
            group: ~
            important: true
        own:
            name: Притежавани
            icon: fa-home
            description: Притежавани книги
            group: ~

    footer_links:
        - { icon: code, url: https://github.com/chitanka/biblioman, text: Изходен код }
        - { icon: database, url: /biblioman.sql.gz, text: База от данни }

    chitanka_wiki.content_dir: "%kernel.root_dir%/../data/wiki"
