parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     biblioman
    database_user:     root
    database_password: ~

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~

    locale:            bg

    # A secret key that's used to generate certain security-related tokens
    secret:            ThisTokenIsNotSoSecretChangeIt
    sitename: Библиоман
    single_login_provider: ~

    book_fields_short:
        - author
        - title
        - subtitle
        - volumeTitle
        - sequence
        - chiefEditor
        - editor
        - publisherEditor
        - translator
        - compiler
        - artist
        - artistEditor
        - technicalEditor
        - publisher
        - publishingDate
        - nationality
        - edition
        - genre
        - category
        - format
        - isbn10
        - isbn13
        - createdBy
    book_fields_long:
        - author
        - title
        - subtitle
        - subtitle2
        - volumeTitle
        - sequence
        - sequenceNr
        - translator
        - translatedFromLanguage
        - dateOfTranslation
        - otherAuthors
        - compiler
        - editorialStaff
        - chiefEditor
        - editor
        - publisherEditor
        - consultant
        - artist
        - artistEditor
        - technicalEditor
        - reviewer
        - corrector
        - layout
        - coverLayout
        - computerProcessing
        - prepress
        - publisher
        - publisherCity
        - publishingDate
        - publisherAddress
        - print
        - contentType
        - nationality
        - language
        - edition
        - litGroup
        - typeSettingIn
        - printSigned
        - printOut
        - printerSheets
        - publisherSheets
        - provisionPublisherSheets
        - format
        - publisherCode
        - trackingCode
        - publisherOrder
        - publisherNumber
        - uniformProductClassification
        - pageCount
        - totalPrint
        - price
        - binding
        - illustrated
        - isbn10
        - isbn13
        - genre
        - themes
        - category
        - annotation
        - marketingSnippets
        - toc
        - notes
        - notesAboutOriginal
        - createdBy
        - createdAt
        - updatedAt
        - infoSources
        - linksByCategory

    footer_links:
        - { icon: code, url: https://github.com/chitanka/biblioman, text: Изходен код }
        - { icon: database, url: /biblioman.sql.gz, text: База от данни }
