parameters:
    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~

    locale:            bg

    # A secret key that's used to generate certain security-related tokens
    secret:            ThisTokenIsNotSoSecretChangeIt
    sitename: Библиоман
    single_login_provider: ~

    book_fields_short:
        - author
        - title
        - subtitle
        - sequence
        - chiefEditor
        - editor
        - publisherEditor
        - translator
        - compiler
        - artist
        - artistEditor
        - technicalEditor
        - publisher
        - pubDate
        - nationality
        - edition
        - genre
        - category
        - format
        - isbn10
        - isbn13
        - createdBy
    book_fields_long:
        - author
        - title
        - subtitle
        - sequence
        - sequenceNr
        - translator
        - translatedFromLanguage
        - dateOfTranslation
        - compiler
        - editorialStaff
        - chiefEditor
        - editor
        - publisherEditor
        - consultant
        - artist
        - artistEditor
        - technicalEditor
        - reviewer
        - corrector
        - layout
        - coverLayout
        - computerProcessing
        - prepress
        - publisher
        - pubCity
        - pubDate
        - publisherAddress
        - print
        - contentType
        - nationality
        - language
        - edition
        - litGroup
        - typeSettingIn
        - printSigned
        - printOut
        - printerSheets
        - publisherSheets
        - provisionPublisherSheets
        - format
        - publisherCode
        - trackingCode
        - publisherOrder
        - publisherNumber
        - uniformProductClassification
        - pageCount
        - totalPrint
        - price
        - binding
        - illustrated
        - isbn10
        - isbn13
        - genre
        - themes
        - category
        - annotation
        - marketingSnippets
        - toc
        - notes
        - notesAboutOriginal
        - linksByCategory
        - createdBy
        - createdAt
        - updatedAt
