easy_admin_bundle:
    #resource: "@EasyAdminBundle/Controller/"
    resource: "@App/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin

app:
    resource: "@App/Controller/"
    type:     annotation
