easy_admin_bundle:
    #resource: "@EasyAdminBundle/Controller/"
    resource: "@App/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin

fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.xml"
    prefix: /messaging

app:
    resource: "@App/Controller/"
    type:     annotation

chitanka_wiki:
    resource: "@ChitankaWikiBundle/Resources/config/routing.yml"
    prefix:   /
