security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        main:
            entity: { class: App\Entity\User, property: username }

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_EDITOR]
        ROLE_EDITOR:      ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false
        default:
            anonymous: ~

    access_control:
        - { path: ^/admin/, roles: [ROLE_ADMIN, ROLE_EDITOR] }
