# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
services:
    kernel.listener:
        class: App\Listener\KernelListener
        arguments: ["@doctrine.orm.entity_manager", "@security.token_storage", "%single_login_provider%"]
        tags:
            - { name: kernel.event_subscriber }

    app.file_namer:
        class: App\File\Namer

    app.user_transformer:
        class: App\Form\DataTransformer\UserToUsernameTransformer
        arguments: ["@doctrine"]

    app.new_message_thread_form_type:
        class: App\Form\NewThreadMessageFormType

    app.new_message_thread_form_factory:
        class: App\Form\NewThreadMessageFormFactory
        arguments: ["@form.factory", "@app.new_message_thread_form_type", "%fos_message.new_thread_form.name%", "%fos_message.new_thread_form.model%", "@app.user_transformer"]
