# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
services:
    kernel.listener:
        class: App\Listener\KernelListener
        arguments: ["@doctrine.orm.entity_manager", "@security.token_storage", "%single_login_provider%"]
        tags:
            - { name: kernel.event_subscriber }
