# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
services:
    kernel.listener:
        class: App\Listener\KernelListener
        arguments: ["@app.repository_finder", "@security.token_storage", "%single_login_provider%", "@twig"]
        tags:
            - { name: kernel.event_subscriber }

    easyadmin.listener:
        class: App\Listener\EasyAdminListener
        tags:
            - { name: kernel.event_subscriber }

    app.file_namer:
        class: App\File\Namer

    app.persistence_manager:
        class: App\Persistence\Manager
        arguments: ["@doctrine"]

    app.repository_finder:
        class: App\Persistence\RepositoryFinder
        arguments: ["@app.persistence_manager"]

    app.user_transformer:
        class: App\Form\DataTransformer\UserToUsernameTransformer
        arguments: ["@doctrine"]

    app.new_message_thread_form_type:
        class: App\Form\Messaging\NewThreadMessageFormType

    app.new_message_thread_form_factory:
        class: App\Form\Messaging\NewThreadMessageFormFactory
        arguments: ["@form.factory", "@app.new_message_thread_form_type", "%fos_message.new_thread_form.name%", "%fos_message.new_thread_form.model%", "@app.user_transformer"]

    app.twig.extension:
        class:     App\Twig\Extension
        arguments: ['@router']
        public:    false
        tags:
            - { name: twig.extension }

    app.shelf_store:
        class: App\Library\ShelfStore
        arguments: ["@app.persistence_manager", "@app.repository_finder"]

    app.librarian:
        class: App\Library\Librarian
        arguments: ["@app.repository_finder"]
